import {
  ArrowsAltOutlined,
  AccountBookFilled,
  AccountBookOutlined,
  AccountBookTwoTone,
  AimOutlined,
  AlertFilled,
  AlertOutlined,
  AlertTwoTone,
  AlibabaOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  AlipayCircleFilled,
  AlipayCircleOutlined,
  AlipayOutlined,
  AlipaySquareFilled,
  AliwangwangFilled,
  AliwangwangOutlined,
  AliyunOutlined,
  AmazonCircleFilled,
  AmazonOutlined,
  AmazonSquareFilled,
  AndroidFilled,
  AndroidOutlined,
  AntCloudOutlined,
  AntDesignOutlined,
  ApartmentOutlined,
  ApiFilled,
  ApiOutlined,
  ApiTwoTone,
  AppleFilled,
  AppleOutlined,
  AppstoreAddOutlined,
  AppstoreFilled,
  AppstoreOutlined,
  AppstoreTwoTone,
  AreaChartOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  AudioFilled,
  AudioMutedOutlined,
  AudioOutlined,
  AudioTwoTone,
  AuditOutlined,
  BackwardFilled,
  BackwardOutlined,
  BankFilled,
  BankOutlined,
  BankTwoTone,
  BarChartOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BehanceCircleFilled,
  BehanceOutlined,
  BehanceSquareFilled,
  BehanceSquareOutlined,
  BellFilled,
  BellOutlined,
  BellTwoTone,
  BgColorsOutlined,
  BlockOutlined,
  BoldOutlined,
  BookFilled,
  BookOutlined,
  BookTwoTone,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  BorderInnerOutlined,
  BorderLeftOutlined,
  BorderOuterOutlined,
  BorderOutlined,
  BorderRightOutlined,
  BorderTopOutlined,
  BorderVerticleOutlined,
  BorderlessTableOutlined,
  BoxPlotFilled,
  BoxPlotOutlined,
  BoxPlotTwoTone,
  BranchesOutlined,
  BugFilled,
  BugOutlined,
  BugTwoTone,
  BuildFilled,
  BuildOutlined,
  BuildTwoTone,
  BulbFilled,
  BulbOutlined,
  BulbTwoTone,
  CalculatorFilled,
  CalculatorOutlined,
  CalculatorTwoTone,
  CalendarFilled,
  CalendarOutlined,
  CalendarTwoTone,
  CameraFilled,
  CameraOutlined,
  CameraTwoTone,
  CarFilled,
  CarOutlined,
  CarTwoTone,
  CaretDownFilled,
  CaretDownOutlined,
  CaretLeftFilled,
  CaretLeftOutlined,
  CaretRightFilled,
  CaretRightOutlined,
  CaretUpFilled,
  CaretUpOutlined,
  CarryOutFilled,
  CarryOutOutlined,
  CarryOutTwoTone,
  CheckCircleFilled,
  CheckCircleOutlined,
  CheckCircleTwoTone,
  CheckOutlined,
  CheckSquareFilled,
  CheckSquareOutlined,
  CheckSquareTwoTone,
  ChromeFilled,
  ChromeOutlined,
  CiCircleFilled,
  CiCircleOutlined,
  CiCircleTwoTone,
  CiOutlined,
  CiTwoTone,
  ClearOutlined,
  ClockCircleFilled,
  ClockCircleOutlined,
  ClockCircleTwoTone,
  CloseCircleFilled,
  CloseCircleOutlined,
  CloseCircleTwoTone,
  CloseOutlined,
  CloseSquareFilled,
  CloseSquareOutlined,
  CloseSquareTwoTone,
  CloudDownloadOutlined,
  CloudFilled,
  CloudOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudTwoTone,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeFilled,
  CodeOutlined,
  CodeSandboxCircleFilled,
  CodeSandboxOutlined,
  CodeSandboxSquareFilled,
  CodeTwoTone,
  CodepenCircleFilled,
  CodepenCircleOutlined,
  CodepenOutlined,
  CodepenSquareFilled,
  CoffeeOutlined,
  ColumnHeightOutlined,
  ColumnWidthOutlined,
  CommentOutlined,
  CompassFilled,
  CompassOutlined,
  CompassTwoTone,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsFilled,
  ContactsOutlined,
  ContactsTwoTone,
  ContainerFilled,
  ContainerOutlined,
  ContainerTwoTone,
  ControlFilled,
  ControlOutlined,
  ControlTwoTone,
  CopyFilled,
  CopyOutlined,
  CopyTwoTone,
  CopyrightCircleFilled,
  CopyrightCircleOutlined,
  CopyrightCircleTwoTone,
  CopyrightOutlined,
  CopyrightTwoTone,
  CreditCardFilled,
  CreditCardOutlined,
  CreditCardTwoTone,
  CrownFilled,
  CrownOutlined,
  CrownTwoTone,
  CustomerServiceFilled,
  CustomerServiceOutlined,
  CustomerServiceTwoTone,
  DashOutlined,
  DashboardFilled,
  DashboardOutlined,
  DashboardTwoTone,
  DatabaseFilled,
  DatabaseOutlined,
  DatabaseTwoTone,
  DeleteColumnOutlined,
  DeleteFilled,
  DeleteOutlined,
  DeleteRowOutlined,
  DeleteTwoTone,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DiffFilled,
  DiffOutlined,
  DiffTwoTone,
  DingdingOutlined,
  DingtalkCircleFilled,
  DingtalkOutlined,
  DingtalkSquareFilled,
  DisconnectOutlined,
  DislikeFilled,
  DislikeOutlined,
  DislikeTwoTone,
  DollarCircleFilled,
  DollarCircleOutlined,
  DollarCircleTwoTone,
  DollarOutlined,
  DollarTwoTone,
  DotChartOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
  DownCircleFilled,
  DownCircleOutlined,
  DownCircleTwoTone,
  DownOutlined,
  DownSquareFilled,
  DownSquareOutlined,
  DownSquareTwoTone,
  DownloadOutlined,
  DragOutlined,
  DribbbleCircleFilled,
  DribbbleOutlined,
  DribbbleSquareFilled,
  DribbbleSquareOutlined,
  DropboxCircleFilled,
  DropboxOutlined,
  DropboxSquareFilled,
  EditFilled,
  EditOutlined,
  EditTwoTone,
  EllipsisOutlined,
  EnterOutlined,
  EnvironmentFilled,
  EnvironmentOutlined,
  EnvironmentTwoTone,
  EuroCircleFilled,
  EuroCircleOutlined,
  EuroCircleTwoTone,
  EuroOutlined,
  EuroTwoTone,
  ExceptionOutlined,
  ExclamationCircleFilled,
  ExclamationCircleOutlined,
  ExclamationCircleTwoTone,
  ExclamationOutlined,
  ExpandAltOutlined,
  ExpandOutlined,
  ExperimentFilled,
  ExperimentOutlined,
  ExperimentTwoTone,
  ExportOutlined,
  EyeFilled,
  EyeInvisibleFilled,
  EyeInvisibleOutlined,
  EyeInvisibleTwoTone,
  EyeOutlined,
  EyeTwoTone,
  FacebookFilled,
  FacebookOutlined,
  FallOutlined,
  FastBackwardFilled,
  FastBackwardOutlined,
  FastForwardFilled,
  FastForwardOutlined,
  FieldBinaryOutlined,
  FieldNumberOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddFilled,
  FileAddOutlined,
  FileAddTwoTone,
  FileDoneOutlined,
  FileExcelFilled,
  FileExcelOutlined,
  FileExcelTwoTone,
  FileExclamationFilled,
  FileExclamationOutlined,
  FileExclamationTwoTone,
  FileFilled,
  FileGifOutlined,
  FileImageFilled,
  FileImageOutlined,
  FileImageTwoTone,
  FileJpgOutlined,
  FileMarkdownFilled,
  FileMarkdownOutlined,
  FileMarkdownTwoTone,
  FileOutlined,
  FilePdfFilled,
  FilePdfOutlined,
  FilePdfTwoTone,
  FilePptFilled,
  FilePptOutlined,
  FilePptTwoTone,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextFilled,
  FileTextOutlined,
  FileTextTwoTone,
  FileTwoTone,
  FileUnknownFilled,
  FileUnknownOutlined,
  FileUnknownTwoTone,
  FileWordFilled,
  FileWordOutlined,
  FileWordTwoTone,
  FileZipFilled,
  FileZipOutlined,
  FileZipTwoTone,
  FilterFilled,
  FilterOutlined,
  FilterTwoTone,
  FireFilled,
  FireOutlined,
  FireTwoTone,
  FlagFilled,
  FlagOutlined,
  FlagTwoTone,
  FolderAddFilled,
  FolderAddOutlined,
  FolderAddTwoTone,
  FolderFilled,
  FolderOpenFilled,
  FolderOpenOutlined,
  FolderOpenTwoTone,
  FolderOutlined,
  FolderTwoTone,
  FolderViewOutlined,
  FontColorsOutlined,
  FontSizeOutlined,
  ForkOutlined,
  FormOutlined,
  FormatPainterFilled,
  FormatPainterOutlined,
  ForwardFilled,
  ForwardOutlined,
  FrownFilled,
  FrownOutlined,
  FrownTwoTone,
  FullscreenExitOutlined,
  FullscreenOutlined,
  FunctionOutlined,
  FundFilled,
  FundOutlined,
  FundProjectionScreenOutlined,
  FundTwoTone,
  FundViewOutlined,
  FunnelPlotFilled,
  FunnelPlotOutlined,
  FunnelPlotTwoTone,
  GatewayOutlined,
  GifOutlined,
  GiftFilled,
  GiftOutlined,
  GiftTwoTone,
  GithubFilled,
  GithubOutlined,
  GitlabFilled,
  GitlabOutlined,
  GlobalOutlined,
  GoldFilled,
  GoldOutlined,
  GoldTwoTone,
  GoldenFilled,
  GoogleCircleFilled,
  GoogleOutlined,
  GooglePlusCircleFilled,
  GooglePlusOutlined,
  GooglePlusSquareFilled,
  GoogleSquareFilled,
  GroupOutlined,
  HddFilled,
  HddOutlined,
  HddTwoTone,
  HeartFilled,
  HeartOutlined,
  HeartTwoTone,
  HeatMapOutlined,
  HighlightFilled,
  HighlightOutlined,
  HighlightTwoTone,
  HistoryOutlined,
  HomeFilled,
  HomeOutlined,
  HomeTwoTone,
  HourglassFilled,
  HourglassOutlined,
  HourglassTwoTone,
  Html5Filled,
  Html5Outlined,
  Html5TwoTone,
  IdcardFilled,
  IdcardOutlined,
  IdcardTwoTone,
  IeCircleFilled,
  IeOutlined,
  IeSquareFilled,
  ImportOutlined,
  InboxOutlined,
  InfoCircleFilled,
  InfoCircleOutlined,
  InfoCircleTwoTone,
  InfoOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsertRowRightOutlined,
  InstagramFilled,
  InstagramOutlined,
  InsuranceFilled,
  InsuranceOutlined,
  InsuranceTwoTone,
  InteractionFilled,
  InteractionOutlined,
  InteractionTwoTone,
  IssuesCloseOutlined,
  ItalicOutlined,
  KeyOutlined,
  LaptopOutlined,
  LayoutFilled,
  LayoutOutlined,
  LayoutTwoTone,
  LeftCircleFilled,
  LeftCircleOutlined,
  LeftCircleTwoTone,
  LeftOutlined,
  LeftSquareFilled,
  LeftSquareOutlined,
  LeftSquareTwoTone,
  LikeFilled,
  LikeOutlined,
  LikeTwoTone,
  LineChartOutlined,
  LineHeightOutlined,
  LineOutlined,
  LinkOutlined,
  LinkedinFilled,
  LinkedinOutlined,
  Loading3QuartersOutlined,
  LoadingOutlined,
  LockFilled,
  LockOutlined,
  LockTwoTone,
  LoginOutlined,
  LogoutOutlined,
  MacCommandFilled,
  MacCommandOutlined,
  MailFilled,
  MailOutlined,
  MailTwoTone,
  ManOutlined,
  MedicineBoxFilled,
  MedicineBoxOutlined,
  MedicineBoxTwoTone,
  MediumCircleFilled,
  MediumOutlined,
  MediumSquareFilled,
  MediumWorkmarkOutlined,
  MehFilled,
  MehOutlined,
  MehTwoTone,
  MenuFoldOutlined,
  MenuOutlined,
  MenuUnfoldOutlined,
  MergeCellsOutlined,
  MessageFilled,
  MessageOutlined,
  MessageTwoTone,
  MinusCircleFilled,
  MinusCircleOutlined,
  MinusCircleTwoTone,
  MinusOutlined,
  MinusSquareFilled,
  MinusSquareOutlined,
  MinusSquareTwoTone,
  MobileFilled,
  MobileOutlined,
  MobileTwoTone,
  MoneyCollectFilled,
  MoneyCollectOutlined,
  MoneyCollectTwoTone,
  MonitorOutlined,
  MoreOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationFilled,
  NotificationOutlined,
  NotificationTwoTone,
  NumberOutlined,
  OneToOneOutlined,
  OrderedListOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PauseCircleFilled,
  PauseCircleOutlined,
  PauseCircleTwoTone,
  PauseOutlined,
  PayCircleFilled,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneFilled,
  PhoneOutlined,
  PhoneTwoTone,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  PictureFilled,
  PictureOutlined,
  PictureTwoTone,
  PieChartFilled,
  PieChartOutlined,
  PieChartTwoTone,
  PlayCircleFilled,
  PlayCircleOutlined,
  PlayCircleTwoTone,
  PlaySquareFilled,
  PlaySquareOutlined,
  PlaySquareTwoTone,
  PlusCircleFilled,
  PlusCircleOutlined,
  PlusCircleTwoTone,
  PlusOutlined,
  PlusSquareFilled,
  PlusSquareOutlined,
  PlusSquareTwoTone,
  PoundCircleFilled,
  PoundCircleOutlined,
  PoundCircleTwoTone,
  PoundOutlined,
  PoweroffOutlined,
  PrinterFilled,
  PrinterOutlined,
  PrinterTwoTone,
  ProfileFilled,
  ProfileOutlined,
  ProfileTwoTone,
  ProjectFilled,
  ProjectOutlined,
  ProjectTwoTone,
  PropertySafetyFilled,
  PropertySafetyOutlined,
  PropertySafetyTwoTone,
  PullRequestOutlined,
  PushpinFilled,
  PushpinOutlined,
  PushpinTwoTone,
  QqCircleFilled,
  QqOutlined,
  QqSquareFilled,
  QrcodeOutlined,
  QuestionCircleFilled,
  QuestionCircleOutlined,
  QuestionCircleTwoTone,
  QuestionOutlined,
  RadarChartOutlined,
  RadiusBottomleftOutlined,
  RadiusBottomrightOutlined,
  RadiusSettingOutlined,
  RadiusUpleftOutlined,
  RadiusUprightOutlined,
  ReadFilled,
  ReadOutlined,
  ReconciliationFilled,
  ReconciliationOutlined,
  ReconciliationTwoTone,
  RedEnvelopeFilled,
  RedEnvelopeOutlined,
  RedEnvelopeTwoTone,
  RedditCircleFilled,
  RedditOutlined,
  RedditSquareFilled,
  RedoOutlined,
  ReloadOutlined,
  RestFilled,
  RestOutlined,
  RestTwoTone,
  RetweetOutlined,
  RightCircleFilled,
  RightCircleOutlined,
  RightCircleTwoTone,
  RightOutlined,
  RightSquareFilled,
  RightSquareOutlined,
  RightSquareTwoTone,
  RiseOutlined,
  RobotFilled,
  RobotOutlined,
  RocketFilled,
  RocketOutlined,
  RocketTwoTone,
  RollbackOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SafetyCertificateFilled,
  SafetyCertificateOutlined,
  SafetyCertificateTwoTone,
  SafetyOutlined,
  SaveFilled,
  SaveOutlined,
  SaveTwoTone,
  ScanOutlined,
  ScheduleFilled,
  ScheduleOutlined,
  ScheduleTwoTone,
  ScissorOutlined,
  SearchOutlined,
  SecurityScanFilled,
  SecurityScanOutlined,
  SecurityScanTwoTone,
  SelectOutlined,
  SendOutlined,
  SettingFilled,
  SettingOutlined,
  SettingTwoTone,
  ShakeOutlined,
  ShareAltOutlined,
  ShopFilled,
  ShopOutlined,
  ShopTwoTone,
  ShoppingCartOutlined,
  ShoppingFilled,
  ShoppingOutlined,
  ShoppingTwoTone,
  ShrinkOutlined,
  SignalFilled,
  SisternodeOutlined,
  SketchCircleFilled,
  SketchOutlined,
  SketchSquareFilled,
  SkinFilled,
  SkinOutlined,
  SkinTwoTone,
  SkypeFilled,
  SkypeOutlined,
  SlackCircleFilled,
  SlackOutlined,
  SlackSquareFilled,
  SlackSquareOutlined,
  SlidersFilled,
  SlidersOutlined,
  SlidersTwoTone,
  SmallDashOutlined,
  SmileFilled,
  SmileOutlined,
  SmileTwoTone,
  SnippetsFilled,
  SnippetsOutlined,
  SnippetsTwoTone,
  SolutionOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  SoundFilled,
  SoundOutlined,
  SoundTwoTone,
  SplitCellsOutlined,
  StarFilled,
  StarOutlined,
  StarTwoTone,
  StepBackwardFilled,
  StepBackwardOutlined,
  StepForwardFilled,
  StepForwardOutlined,
  StockOutlined,
  StopFilled,
  StopOutlined,
  StopTwoTone,
  StrikethroughOutlined,
  SubnodeOutlined,
  SwapLeftOutlined,
  SwapOutlined,
  SwapRightOutlined,
  SwitcherFilled,
  SwitcherOutlined,
  SwitcherTwoTone,
  SyncOutlined,
  TableOutlined,
  TabletFilled,
  TabletOutlined,
  TabletTwoTone,
  TagFilled,
  TagOutlined,
  TagTwoTone,
  TagsFilled,
  TagsOutlined,
  TagsTwoTone,
  TaobaoCircleFilled,
  TaobaoCircleOutlined,
  TaobaoOutlined,
  TaobaoSquareFilled,
  TeamOutlined,
  ThunderboltFilled,
  ThunderboltOutlined,
  ThunderboltTwoTone,
  ToTopOutlined,
  ToolFilled,
  ToolOutlined,
  ToolTwoTone,
  TrademarkCircleFilled,
  TrademarkCircleOutlined,
  TrademarkCircleTwoTone,
  TrademarkOutlined,
  TransactionOutlined,
  TranslationOutlined,
  TrophyFilled,
  TrophyOutlined,
  TrophyTwoTone,
  TwitterCircleFilled,
  TwitterOutlined,
  TwitterSquareFilled,
  UnderlineOutlined,
  UndoOutlined,
  UngroupOutlined,
  UnlockFilled,
  UnlockOutlined,
  UnlockTwoTone,
  UnorderedListOutlined,
  UpCircleFilled,
  UpCircleOutlined,
  UpCircleTwoTone,
  UpOutlined,
  UpSquareFilled,
  UpSquareOutlined,
  UpSquareTwoTone,
  UploadOutlined,
  UsbFilled,
  UsbOutlined,
  UsbTwoTone,
  UserAddOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  VerifiedOutlined,
  VerticalAlignBottomOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignTopOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VideoCameraAddOutlined,
  VideoCameraFilled,
  VideoCameraOutlined,
  VideoCameraTwoTone,
  WalletFilled,
  WalletOutlined,
  WalletTwoTone,
  WarningFilled,
  WarningOutlined,
  WarningTwoTone,
  WechatFilled,
  WechatOutlined,
  WeiboCircleFilled,
  WeiboCircleOutlined,
  WeiboOutlined,
  WeiboSquareFilled,
  WeiboSquareOutlined,
  WhatsAppOutlined,
  WifiOutlined,
  WindowsFilled,
  WindowsOutlined,
  WomanOutlined,
  YahooFilled,
  YahooOutlined,
  YoutubeFilled,
  YoutubeOutlined,
  YuqueFilled,
  YuqueOutlined,
  ZhihuCircleFilled,
  ZhihuOutlined,
  ZhihuSquareFilled,
  ZoomInOutlined,
  ZoomOutOutlined
} from '@ant-design/icons'

export const IconList = [
  { label: 'AccountBookFilled', Icon: AccountBookFilled },
  { label: 'AccountBookOutlined', Icon: AccountBookOutlined },
  { label: 'AimOutlined', Icon: AimOutlined },
  { label: 'AlertFilled', Icon: AlertFilled },
  { label: 'AlertOutlined', Icon: AlertOutlined },
  { label: 'AlibabaOutlined', Icon: AlibabaOutlined },
  { label: 'AlignCenterOutlined', Icon: AlignCenterOutlined },
  { label: 'AlignLeftOutlined', Icon: AlignLeftOutlined },
  { label: 'AlignRightOutlined', Icon: AlignRightOutlined },
  { label: 'AlipayCircleFilled', Icon: AlipayCircleFilled },
  { label: 'AlipayCircleOutlined', Icon: AlipayCircleOutlined },
  { label: 'AlipayOutlined', Icon: AlipayOutlined },
  { label: 'AlipaySquareFilled', Icon: AlipaySquareFilled },
  { label: 'AliwangwangFilled', Icon: AliwangwangFilled },
  { label: 'AliwangwangOutlined', Icon: AliwangwangOutlined },
  { label: 'AliyunOutlined', Icon: AliyunOutlined },
  { label: 'AmazonCircleFilled', Icon: AmazonCircleFilled },
  { label: 'AmazonOutlined', Icon: AmazonOutlined },
  { label: 'AmazonSquareFilled', Icon: AmazonSquareFilled },
  { label: 'AndroidFilled', Icon: AndroidFilled },
  { label: 'AndroidOutlined', Icon: AndroidOutlined },
  { label: 'AntCloudOutlined', Icon: AntCloudOutlined },
  { label: 'AntDesignOutlined', Icon: AntDesignOutlined },
  { label: 'ApartmentOutlined', Icon: ApartmentOutlined },
  { label: 'ApiFilled', Icon: ApiFilled },
  { label: 'ApiOutlined', Icon: ApiOutlined },
  { label: 'AppleFilled', Icon: AppleFilled },
  { label: 'AppleOutlined', Icon: AppleOutlined },
  { label: 'AppstoreAddOutlined', Icon: AppstoreAddOutlined },
  { label: 'AppstoreFilled', Icon: AppstoreFilled },
  { label: 'AppstoreOutlined', Icon: AppstoreOutlined },
  { label: 'AreaChartOutlined', Icon: AreaChartOutlined },
  { label: 'ArrowDownOutlined', Icon: ArrowDownOutlined },
  { label: 'ArrowLeftOutlined', Icon: ArrowLeftOutlined },
  { label: 'ArrowRightOutlined', Icon: ArrowRightOutlined },
  { label: 'ArrowUpOutlined', Icon: ArrowUpOutlined },
  { label: 'ArrowsAltOutlined', Icon: ArrowsAltOutlined },
  { label: 'AudioFilled', Icon: AudioFilled },
  { label: 'AudioMutedOutlined', Icon: AudioMutedOutlined },
  { label: 'AudioOutlined', Icon: AudioOutlined },
  { label: 'AuditOutlined', Icon: AuditOutlined },
  { label: 'BackwardFilled', Icon: BackwardFilled },
  { label: 'BackwardOutlined', Icon: BackwardOutlined },
  { label: 'BankFilled', Icon: BankFilled },
  { label: 'BankOutlined', Icon: BankOutlined },
  { label: 'BarChartOutlined', Icon: BarChartOutlined },
  { label: 'BarcodeOutlined', Icon: BarcodeOutlined },
  { label: 'BarsOutlined', Icon: BarsOutlined },
  { label: 'BehanceCircleFilled', Icon: BehanceCircleFilled },
  { label: 'BehanceOutlined', Icon: BehanceOutlined },
  { label: 'BehanceSquareFilled', Icon: BehanceSquareFilled },
  { label: 'BehanceSquareOutlined', Icon: BehanceSquareOutlined },
  { label: 'BellFilled', Icon: BellFilled },
  { label: 'BellOutlined', Icon: BellOutlined },
  { label: 'BgColorsOutlined', Icon: BgColorsOutlined },
  { label: 'BlockOutlined', Icon: BlockOutlined },
  { label: 'BoldOutlined', Icon: BoldOutlined },
  { label: 'BookFilled', Icon: BookFilled },
  { label: 'BookOutlined', Icon: BookOutlined },
  { label: 'BellTwoTone', Icon: BellTwoTone },
  { label: 'BookTwoTone', Icon: BookTwoTone },
  { label: 'BankTwoTone', Icon: BankTwoTone },
  { label: 'ApiTwoTone', Icon: ApiTwoTone },
  { label: 'AlertTwoTone', Icon: AlertTwoTone },
  { label: 'AccountBookTwoTone', Icon: AccountBookTwoTone },
  { label: 'AppstoreTwoTone', Icon: AppstoreTwoTone },
  { label: 'AudioTwoTone', Icon: AudioTwoTone },
  { label: 'BugTwoTone', Icon: BugTwoTone },
  { label: 'BuildTwoTone', Icon: BuildTwoTone },
  { label: 'BulbTwoTone', Icon: BulbTwoTone },
  { label: 'BoxPlotTwoTone', Icon: BoxPlotTwoTone },
  { label: 'CalculatorTwoTone', Icon: CalculatorTwoTone },
  { label: 'CarTwoTone', Icon: CarTwoTone },
  { label: 'CameraTwoTone', Icon: CameraTwoTone },
  { label: 'CheckSquareTwoTone', Icon: CheckSquareTwoTone },
  { label: 'CarryOutTwoTone', Icon: CarryOutTwoTone },
  { label: 'CalendarTwoTone', Icon: CalendarTwoTone },
  { label: 'CheckCircleTwoTone', Icon: CheckCircleTwoTone },
  { label: 'BorderBottomOutlined', Icon: BorderBottomOutlined },
  { label: 'BorderHorizontalOutlined', Icon: BorderHorizontalOutlined },
  { label: 'BorderInnerOutlined', Icon: BorderInnerOutlined },
  { label: 'BorderLeftOutlined', Icon: BorderLeftOutlined },
  { label: 'BorderOuterOutlined', Icon: BorderOuterOutlined },
  { label: 'BorderOutlined', Icon: BorderOutlined },
  { label: 'BorderRightOutlined', Icon: BorderRightOutlined },
  { label: 'BorderTopOutlined', Icon: BorderTopOutlined },
  { label: 'BorderVerticleOutlined', Icon: BorderVerticleOutlined },
  { label: 'BorderlessTableOutlined', Icon: BorderlessTableOutlined },
  { label: 'BoxPlotFilled', Icon: BoxPlotFilled },
  { label: 'BoxPlotOutlined', Icon: BoxPlotOutlined },
  { label: 'BranchesOutlined', Icon: BranchesOutlined },
  { label: 'BugFilled', Icon: BugFilled },
  { label: 'BugOutlined', Icon: BugOutlined },
  { label: 'BuildFilled', Icon: BuildFilled },
  { label: 'BuildOutlined', Icon: BuildOutlined },
  { label: 'BulbFilled', Icon: BulbFilled },
  { label: 'BulbOutlined', Icon: BulbOutlined },
  { label: 'CalculatorFilled', Icon: CalculatorFilled },
  { label: 'CalculatorOutlined', Icon: CalculatorOutlined },
  { label: 'CalendarFilled', Icon: CalendarFilled },
  { label: 'CalendarOutlined', Icon: CalendarOutlined },
  { label: 'CameraFilled', Icon: CameraFilled },
  { label: 'CameraOutlined', Icon: CameraOutlined },
  { label: 'CarFilled', Icon: CarFilled },
  { label: 'CarOutlined', Icon: CarOutlined },
  { label: 'CaretDownFilled', Icon: CaretDownFilled },
  { label: 'CaretDownOutlined', Icon: CaretDownOutlined },
  { label: 'CaretLeftFilled', Icon: CaretLeftFilled },
  { label: 'CaretLeftOutlined', Icon: CaretLeftOutlined },
  { label: 'CaretRightFilled', Icon: CaretRightFilled },
  { label: 'CaretRightOutlined', Icon: CaretRightOutlined },
  { label: 'CaretUpFilled', Icon: CaretUpFilled },
  { label: 'CaretUpOutlined', Icon: CaretUpOutlined },
  { label: 'CarryOutFilled', Icon: CarryOutFilled },
  { label: 'CarryOutOutlined', Icon: CarryOutOutlined },
  { label: 'CheckCircleFilled', Icon: CheckCircleFilled },
  { label: 'CheckCircleOutlined', Icon: CheckCircleOutlined },
  { label: 'CheckOutlined', Icon: CheckOutlined },
  { label: 'CheckSquareFilled', Icon: CheckSquareFilled },
  { label: 'CheckSquareOutlined', Icon: CheckSquareOutlined },
  { label: 'ChromeFilled', Icon: ChromeFilled },
  { label: 'ChromeOutlined', Icon: ChromeOutlined },
  { label: 'CiCircleFilled', Icon: CiCircleFilled },
  { label: 'CiCircleOutlined', Icon: CiCircleOutlined },
  { label: 'CiCircleTwoTone', Icon: CiCircleTwoTone },
  { label: 'CiOutlined', Icon: CiOutlined },
  { label: 'CiTwoTone', Icon: CiTwoTone },
  { label: 'ClearOutlined', Icon: ClearOutlined },
  { label: 'ClockCircleFilled', Icon: ClockCircleFilled },
  { label: 'ClockCircleOutlined', Icon: ClockCircleOutlined },
  { label: 'ClockCircleTwoTone', Icon: ClockCircleTwoTone },
  { label: 'CloseCircleFilled', Icon: CloseCircleFilled },
  { label: 'CloseCircleOutlined', Icon: CloseCircleOutlined },
  { label: 'CloseCircleTwoTone', Icon: CloseCircleTwoTone },
  { label: 'CloseOutlined', Icon: CloseOutlined },
  { label: 'CloseSquareFilled', Icon: CloseSquareFilled },
  { label: 'CloseSquareOutlined', Icon: CloseSquareOutlined },
  { label: 'CloseSquareTwoTone', Icon: CloseSquareTwoTone },
  { label: 'CloudDownloadOutlined', Icon: CloudDownloadOutlined },
  { label: 'CloudFilled', Icon: CloudFilled },
  { label: 'CloudOutlined', Icon: CloudOutlined },
  { label: 'CloudServerOutlined', Icon: CloudServerOutlined },
  { label: 'CloudSyncOutlined', Icon: CloudSyncOutlined },
  { label: 'CloudTwoTone', Icon: CloudTwoTone },
  { label: 'CloudUploadOutlined', Icon: CloudUploadOutlined },
  { label: 'ClusterOutlined', Icon: ClusterOutlined },
  { label: 'CodeFilled', Icon: CodeFilled },
  { label: 'CodeOutlined', Icon: CodeOutlined },
  { label: 'CodeSandboxCircleFilled', Icon: CodeSandboxCircleFilled },
  { label: 'CodeSandboxOutlined', Icon: CodeSandboxOutlined },
  { label: 'CodeSandboxSquareFilled', Icon: CodeSandboxSquareFilled },
  { label: 'CodeTwoTone', Icon: CodeTwoTone },
  { label: 'CodepenCircleFilled', Icon: CodepenCircleFilled },
  { label: 'CodepenCircleOutlined', Icon: CodepenCircleOutlined },
  { label: 'CodepenOutlined', Icon: CodepenOutlined },
  { label: 'CodepenSquareFilled', Icon: CodepenSquareFilled },
  { label: 'CoffeeOutlined', Icon: CoffeeOutlined },
  { label: 'ColumnHeightOutlined', Icon: ColumnHeightOutlined },
  { label: 'ColumnWidthOutlined', Icon: ColumnWidthOutlined },
  { label: 'CommentOutlined', Icon: CommentOutlined },
  { label: 'CompassFilled', Icon: CompassFilled },
  { label: 'CompassOutlined', Icon: CompassOutlined },
  { label: 'CompassTwoTone', Icon: CompassTwoTone },
  { label: 'CompressOutlined', Icon: CompressOutlined },
  { label: 'ConsoleSqlOutlined', Icon: ConsoleSqlOutlined },
  { label: 'ContactsFilled', Icon: ContactsFilled },
  { label: 'ContactsOutlined', Icon: ContactsOutlined },
  { label: 'ContactsTwoTone', Icon: ContactsTwoTone },
  { label: 'ContainerFilled', Icon: ContainerFilled },
  { label: 'ContainerOutlined', Icon: ContainerOutlined },
  { label: 'ContainerTwoTone', Icon: ContainerTwoTone },
  { label: 'ControlFilled', Icon: ControlFilled },
  { label: 'ControlOutlined', Icon: ControlOutlined },
  { label: 'ControlTwoTone', Icon: ControlTwoTone },
  { label: 'CopyFilled', Icon: CopyFilled },
  { label: 'CopyOutlined', Icon: CopyOutlined },
  { label: 'CopyTwoTone', Icon: CopyTwoTone },
  { label: 'CopyrightCircleFilled', Icon: CopyrightCircleFilled },
  { label: 'CopyrightCircleOutlined', Icon: CopyrightCircleOutlined },
  { label: 'CopyrightCircleTwoTone', Icon: CopyrightCircleTwoTone },
  { label: 'CopyrightOutlined', Icon: CopyrightOutlined },
  { label: 'CopyrightTwoTone', Icon: CopyrightTwoTone },
  { label: 'CreditCardFilled', Icon: CreditCardFilled },
  { label: 'CreditCardOutlined', Icon: CreditCardOutlined },
  { label: 'CreditCardTwoTone', Icon: CreditCardTwoTone },
  { label: 'CrownFilled', Icon: CrownFilled },
  { label: 'CrownOutlined', Icon: CrownOutlined },
  { label: 'CrownTwoTone', Icon: CrownTwoTone },
  { label: 'CustomerServiceFilled', Icon: CustomerServiceFilled },
  { label: 'CustomerServiceOutlined', Icon: CustomerServiceOutlined },
  { label: 'CustomerServiceTwoTone', Icon: CustomerServiceTwoTone },
  { label: 'DashOutlined', Icon: DashOutlined },
  { label: 'DashboardFilled', Icon: DashboardFilled },
  { label: 'DashboardOutlined', Icon: DashboardOutlined },
  { label: 'DashboardTwoTone', Icon: DashboardTwoTone },
  { label: 'DatabaseFilled', Icon: DatabaseFilled },
  { label: 'DatabaseOutlined', Icon: DatabaseOutlined },
  { label: 'DatabaseTwoTone', Icon: DatabaseTwoTone },
  { label: 'DeleteColumnOutlined', Icon: DeleteColumnOutlined },
  { label: 'DeleteFilled', Icon: DeleteFilled },
  { label: 'DeleteOutlined', Icon: DeleteOutlined },
  { label: 'DeleteRowOutlined', Icon: DeleteRowOutlined },
  { label: 'DeleteTwoTone', Icon: DeleteTwoTone },
  { label: 'DeliveredProcedureOutlined', Icon: DeliveredProcedureOutlined },
  { label: 'DeploymentUnitOutlined', Icon: DeploymentUnitOutlined },
  { label: 'DesktopOutlined', Icon: DesktopOutlined },
  { label: 'DiffFilled', Icon: DiffFilled },
  { label: 'DiffOutlined', Icon: DiffOutlined },
  { label: 'DiffTwoTone', Icon: DiffTwoTone },
  { label: 'DingdingOutlined', Icon: DingdingOutlined },
  { label: 'DingtalkCircleFilled', Icon: DingtalkCircleFilled },
  { label: 'DingtalkOutlined', Icon: DingtalkOutlined },
  { label: 'DingtalkSquareFilled', Icon: DingtalkSquareFilled },
  { label: 'DisconnectOutlined', Icon: DisconnectOutlined },
  { label: 'DislikeFilled', Icon: DislikeFilled },
  { label: 'DislikeOutlined', Icon: DislikeOutlined },
  { label: 'DislikeTwoTone', Icon: DislikeTwoTone },
  { label: 'DollarCircleFilled', Icon: DollarCircleFilled },
  { label: 'DollarCircleOutlined', Icon: DollarCircleOutlined },
  { label: 'DollarCircleTwoTone', Icon: DollarCircleTwoTone },
  { label: 'DollarOutlined', Icon: DollarOutlined },
  { label: 'DollarTwoTone', Icon: DollarTwoTone },
  { label: 'DotChartOutlined', Icon: DotChartOutlined },
  { label: 'DoubleLeftOutlined', Icon: DoubleLeftOutlined },
  { label: 'DoubleRightOutlined', Icon: DoubleRightOutlined },
  { label: 'DownCircleFilled', Icon: DownCircleFilled },
  { label: 'DownCircleOutlined', Icon: DownCircleOutlined },
  { label: 'DownCircleTwoTone', Icon: DownCircleTwoTone },
  { label: 'DownOutlined', Icon: DownOutlined },
  { label: 'DownSquareFilled', Icon: DownSquareFilled },
  { label: 'DownSquareOutlined', Icon: DownSquareOutlined },
  { label: 'DownSquareTwoTone', Icon: DownSquareTwoTone },
  { label: 'DownloadOutlined', Icon: DownloadOutlined },
  { label: 'DragOutlined', Icon: DragOutlined },
  { label: 'DribbbleCircleFilled', Icon: DribbbleCircleFilled },
  { label: 'DribbbleOutlined', Icon: DribbbleOutlined },
  { label: 'DribbbleSquareFilled', Icon: DribbbleSquareFilled },
  { label: 'DribbbleSquareOutlined', Icon: DribbbleSquareOutlined },
  { label: 'DropboxCircleFilled', Icon: DropboxCircleFilled },
  { label: 'DropboxOutlined', Icon: DropboxOutlined },
  { label: 'DropboxSquareFilled', Icon: DropboxSquareFilled },
  { label: 'EditFilled', Icon: EditFilled },
  { label: 'EditOutlined', Icon: EditOutlined },
  { label: 'EditTwoTone', Icon: EditTwoTone },
  { label: 'EllipsisOutlined', Icon: EllipsisOutlined },
  { label: 'EnterOutlined', Icon: EnterOutlined },
  { label: 'EnvironmentFilled', Icon: EnvironmentFilled },
  { label: 'EnvironmentOutlined', Icon: EnvironmentOutlined },
  { label: 'EnvironmentTwoTone', Icon: EnvironmentTwoTone },
  { label: 'EuroCircleFilled', Icon: EuroCircleFilled },
  { label: 'EuroCircleOutlined', Icon: EuroCircleOutlined },
  { label: 'EuroCircleTwoTone', Icon: EuroCircleTwoTone },
  { label: 'EuroOutlined', Icon: EuroOutlined },
  { label: 'EuroTwoTone', Icon: EuroTwoTone },
  { label: 'ExceptionOutlined', Icon: ExceptionOutlined },
  { label: 'ExclamationCircleFilled', Icon: ExclamationCircleFilled },
  { label: 'ExclamationCircleOutlined', Icon: ExclamationCircleOutlined },
  { label: 'ExclamationCircleTwoTone', Icon: ExclamationCircleTwoTone },
  { label: 'ExclamationOutlined', Icon: ExclamationOutlined },
  { label: 'ExpandAltOutlined', Icon: ExpandAltOutlined },
  { label: 'ExpandOutlined', Icon: ExpandOutlined },
  { label: 'ExperimentFilled', Icon: ExperimentFilled },
  { label: 'ExperimentOutlined', Icon: ExperimentOutlined },
  { label: 'ExperimentTwoTone', Icon: ExperimentTwoTone },
  { label: 'ExportOutlined', Icon: ExportOutlined },
  { label: 'EyeFilled', Icon: EyeFilled },
  { label: 'EyeInvisibleFilled', Icon: EyeInvisibleFilled },
  { label: 'EyeInvisibleOutlined', Icon: EyeInvisibleOutlined },
  { label: 'EyeInvisibleTwoTone', Icon: EyeInvisibleTwoTone },
  { label: 'EyeOutlined', Icon: EyeOutlined },
  { label: 'EyeTwoTone', Icon: EyeTwoTone },
  { label: 'FacebookFilled', Icon: FacebookFilled },
  { label: 'FacebookOutlined', Icon: FacebookOutlined },
  { label: 'FallOutlined', Icon: FallOutlined },
  { label: 'FastBackwardFilled', Icon: FastBackwardFilled },
  { label: 'FastBackwardOutlined', Icon: FastBackwardOutlined },
  { label: 'FastForwardFilled', Icon: FastForwardFilled },
  { label: 'FastForwardOutlined', Icon: FastForwardOutlined },
  { label: 'FieldBinaryOutlined', Icon: FieldBinaryOutlined },
  { label: 'FieldNumberOutlined', Icon: FieldNumberOutlined },
  { label: 'FieldStringOutlined', Icon: FieldStringOutlined },
  { label: 'FieldTimeOutlined', Icon: FieldTimeOutlined },
  { label: 'FileAddFilled', Icon: FileAddFilled },
  { label: 'FileAddOutlined', Icon: FileAddOutlined },
  { label: 'FileAddTwoTone', Icon: FileAddTwoTone },
  { label: 'FileDoneOutlined', Icon: FileDoneOutlined },
  { label: 'FileExcelFilled', Icon: FileExcelFilled },
  { label: 'FileExcelOutlined', Icon: FileExcelOutlined },
  { label: 'FileExcelTwoTone', Icon: FileExcelTwoTone },
  { label: 'FileExclamationFilled', Icon: FileExclamationFilled },
  { label: 'FileExclamationOutlined', Icon: FileExclamationOutlined },
  { label: 'FileExclamationTwoTone', Icon: FileExclamationTwoTone },
  { label: 'FileFilled', Icon: FileFilled },
  { label: 'FileGifOutlined', Icon: FileGifOutlined },
  { label: 'FileImageFilled', Icon: FileImageFilled },
  { label: 'FileImageOutlined', Icon: FileImageOutlined },
  { label: 'FileImageTwoTone', Icon: FileImageTwoTone },
  { label: 'FileJpgOutlined', Icon: FileJpgOutlined },
  { label: 'FileMarkdownFilled', Icon: FileMarkdownFilled },
  { label: 'FileMarkdownOutlined', Icon: FileMarkdownOutlined },
  { label: 'FileMarkdownTwoTone', Icon: FileMarkdownTwoTone },
  { label: 'FileOutlined', Icon: FileOutlined },
  { label: 'FilePdfFilled', Icon: FilePdfFilled },
  { label: 'FilePdfOutlined', Icon: FilePdfOutlined },
  { label: 'FilePdfTwoTone', Icon: FilePdfTwoTone },
  { label: 'FilePptFilled', Icon: FilePptFilled },
  { label: 'FilePptOutlined', Icon: FilePptOutlined },
  { label: 'FilePptTwoTone', Icon: FilePptTwoTone },
  { label: 'FileProtectOutlined', Icon: FileProtectOutlined },
  { label: 'FileSearchOutlined', Icon: FileSearchOutlined },
  { label: 'FileSyncOutlined', Icon: FileSyncOutlined },
  { label: 'FileTextFilled', Icon: FileTextFilled },
  { label: 'FileTextOutlined', Icon: FileTextOutlined },
  { label: 'FileTextTwoTone', Icon: FileTextTwoTone },
  { label: 'FileTwoTone', Icon: FileTwoTone },
  { label: 'FileUnknownFilled', Icon: FileUnknownFilled },
  { label: 'FileUnknownOutlined', Icon: FileUnknownOutlined },
  { label: 'FileUnknownTwoTone', Icon: FileUnknownTwoTone },
  { label: 'FileWordFilled', Icon: FileWordFilled },
  { label: 'FileWordOutlined', Icon: FileWordOutlined },
  { label: 'FileWordTwoTone', Icon: FileWordTwoTone },
  { label: 'FileZipFilled', Icon: FileZipFilled },
  { label: 'FileZipOutlined', Icon: FileZipOutlined },
  { label: 'FileZipTwoTone', Icon: FileZipTwoTone },
  { label: 'FilterFilled', Icon: FilterFilled },
  { label: 'FilterOutlined', Icon: FilterOutlined },
  { label: 'FilterTwoTone', Icon: FilterTwoTone },
  { label: 'FireFilled', Icon: FireFilled },
  { label: 'FireOutlined', Icon: FireOutlined },
  { label: 'FireTwoTone', Icon: FireTwoTone },
  { label: 'FlagFilled', Icon: FlagFilled },
  { label: 'FlagOutlined', Icon: FlagOutlined },
  { label: 'FlagTwoTone', Icon: FlagTwoTone },
  { label: 'FolderAddFilled', Icon: FolderAddFilled },
  { label: 'FolderAddOutlined', Icon: FolderAddOutlined },
  { label: 'FolderAddTwoTone', Icon: FolderAddTwoTone },
  { label: 'FolderFilled', Icon: FolderFilled },
  { label: 'FolderOpenFilled', Icon: FolderOpenFilled },
  { label: 'FolderOpenOutlined', Icon: FolderOpenOutlined },
  { label: 'FolderOpenTwoTone', Icon: FolderOpenTwoTone },
  { label: 'FolderOutlined', Icon: FolderOutlined },
  { label: 'FolderTwoTone', Icon: FolderTwoTone },
  { label: 'FolderViewOutlined', Icon: FolderViewOutlined },
  { label: 'FontColorsOutlined', Icon: FontColorsOutlined },
  { label: 'FontSizeOutlined', Icon: FontSizeOutlined },
  { label: 'ForkOutlined', Icon: ForkOutlined },
  { label: 'FormOutlined', Icon: FormOutlined },
  { label: 'FormatPainterFilled', Icon: FormatPainterFilled },
  { label: 'FormatPainterOutlined', Icon: FormatPainterOutlined },
  { label: 'ForwardFilled', Icon: ForwardFilled },
  { label: 'ForwardOutlined', Icon: ForwardOutlined },
  { label: 'FrownFilled', Icon: FrownFilled },
  { label: 'FrownOutlined', Icon: FrownOutlined },
  { label: 'FrownTwoTone', Icon: FrownTwoTone },
  { label: 'FullscreenExitOutlined', Icon: FullscreenExitOutlined },
  { label: 'FullscreenOutlined', Icon: FullscreenOutlined },
  { label: 'FunctionOutlined', Icon: FunctionOutlined },
  { label: 'FundFilled', Icon: FundFilled },
  { label: 'FundOutlined', Icon: FundOutlined },
  { label: 'FundProjectionScreenOutlined', Icon: FundProjectionScreenOutlined },
  { label: 'FundTwoTone', Icon: FundTwoTone },
  { label: 'FundViewOutlined', Icon: FundViewOutlined },
  { label: 'FunnelPlotFilled', Icon: FunnelPlotFilled },
  { label: 'FunnelPlotOutlined', Icon: FunnelPlotOutlined },
  { label: 'FunnelPlotTwoTone', Icon: FunnelPlotTwoTone },
  { label: 'GatewayOutlined', Icon: GatewayOutlined },
  { label: 'GifOutlined', Icon: GifOutlined },
  { label: 'GiftFilled', Icon: GiftFilled },
  { label: 'GiftOutlined', Icon: GiftOutlined },
  { label: 'GiftTwoTone', Icon: GiftTwoTone },
  { label: 'GithubFilled', Icon: GithubFilled },
  { label: 'GithubOutlined', Icon: GithubOutlined },
  { label: 'GitlabFilled', Icon: GitlabFilled },
  { label: 'GitlabOutlined', Icon: GitlabOutlined },
  { label: 'GlobalOutlined', Icon: GlobalOutlined },
  { label: 'GoldFilled', Icon: GoldFilled },
  { label: 'GoldOutlined', Icon: GoldOutlined },
  { label: 'GoldTwoTone', Icon: GoldTwoTone },
  { label: 'GoldenFilled', Icon: GoldenFilled },
  { label: 'GoogleCircleFilled', Icon: GoogleCircleFilled },
  { label: 'GoogleOutlined', Icon: GoogleOutlined },
  { label: 'GooglePlusCircleFilled', Icon: GooglePlusCircleFilled },
  { label: 'GooglePlusOutlined', Icon: GooglePlusOutlined },
  { label: 'GooglePlusSquareFilled', Icon: GooglePlusSquareFilled },
  { label: 'GoogleSquareFilled', Icon: GoogleSquareFilled },
  { label: 'GroupOutlined', Icon: GroupOutlined },
  { label: 'HddFilled', Icon: HddFilled },
  { label: 'HddOutlined', Icon: HddOutlined },
  { label: 'HddTwoTone', Icon: HddTwoTone },
  { label: 'HeartFilled', Icon: HeartFilled },
  { label: 'HeartOutlined', Icon: HeartOutlined },
  { label: 'HeartTwoTone', Icon: HeartTwoTone },
  { label: 'HeatMapOutlined', Icon: HeatMapOutlined },
  { label: 'HighlightFilled', Icon: HighlightFilled },
  { label: 'HighlightOutlined', Icon: HighlightOutlined },
  { label: 'HighlightTwoTone', Icon: HighlightTwoTone },
  { label: 'HistoryOutlined', Icon: HistoryOutlined },
  { label: 'HomeFilled', Icon: HomeFilled },
  { label: 'HomeOutlined', Icon: HomeOutlined },
  { label: 'HomeTwoTone', Icon: HomeTwoTone },
  { label: 'HourglassFilled', Icon: HourglassFilled },
  { label: 'HourglassOutlined', Icon: HourglassOutlined },
  { label: 'HourglassTwoTone', Icon: HourglassTwoTone },
  { label: 'Html5Filled', Icon: Html5Filled },
  { label: 'Html5Outlined', Icon: Html5Outlined },
  { label: 'Html5TwoTone', Icon: Html5TwoTone },
  { label: 'IdcardFilled', Icon: IdcardFilled },
  { label: 'IdcardOutlined', Icon: IdcardOutlined },
  { label: 'IdcardTwoTone', Icon: IdcardTwoTone },
  { label: 'IeCircleFilled', Icon: IeCircleFilled },
  { label: 'IeOutlined', Icon: IeOutlined },
  { label: 'IeSquareFilled', Icon: IeSquareFilled },
  { label: 'ImportOutlined', Icon: ImportOutlined },
  { label: 'InboxOutlined', Icon: InboxOutlined },
  { label: 'InfoCircleFilled', Icon: InfoCircleFilled },
  { label: 'InfoCircleOutlined', Icon: InfoCircleOutlined },
  { label: 'InfoCircleTwoTone', Icon: InfoCircleTwoTone },
  { label: 'InfoOutlined', Icon: InfoOutlined },
  { label: 'InsertRowAboveOutlined', Icon: InsertRowAboveOutlined },
  { label: 'InsertRowBelowOutlined', Icon: InsertRowBelowOutlined },
  { label: 'InsertRowLeftOutlined', Icon: InsertRowLeftOutlined },
  { label: 'InsertRowRightOutlined', Icon: InsertRowRightOutlined },
  { label: 'InstagramFilled', Icon: InstagramFilled },
  { label: 'InstagramOutlined', Icon: InstagramOutlined },
  { label: 'InsuranceFilled', Icon: InsuranceFilled },
  { label: 'InsuranceOutlined', Icon: InsuranceOutlined },
  { label: 'InsuranceTwoTone', Icon: InsuranceTwoTone },
  { label: 'InteractionFilled', Icon: InteractionFilled },
  { label: 'InteractionOutlined', Icon: InteractionOutlined },
  { label: 'InteractionTwoTone', Icon: InteractionTwoTone },
  { label: 'IssuesCloseOutlined', Icon: IssuesCloseOutlined },
  { label: 'ItalicOutlined', Icon: ItalicOutlined },
  { label: 'KeyOutlined', Icon: KeyOutlined },
  { label: 'LaptopOutlined', Icon: LaptopOutlined },
  { label: 'LayoutFilled', Icon: LayoutFilled },
  { label: 'LayoutOutlined', Icon: LayoutOutlined },
  { label: 'LayoutTwoTone', Icon: LayoutTwoTone },
  { label: 'LeftCircleFilled', Icon: LeftCircleFilled },
  { label: 'LeftCircleOutlined', Icon: LeftCircleOutlined },
  { label: 'LeftCircleTwoTone', Icon: LeftCircleTwoTone },
  { label: 'LeftOutlined', Icon: LeftOutlined },
  { label: 'LeftSquareFilled', Icon: LeftSquareFilled },
  { label: 'LeftSquareOutlined', Icon: LeftSquareOutlined },
  { label: 'LeftSquareTwoTone', Icon: LeftSquareTwoTone },
  { label: 'LikeFilled', Icon: LikeFilled },
  { label: 'LikeOutlined', Icon: LikeOutlined },
  { label: 'LikeTwoTone', Icon: LikeTwoTone },
  { label: 'LineChartOutlined', Icon: LineChartOutlined },
  { label: 'LineHeightOutlined', Icon: LineHeightOutlined },
  { label: 'LineOutlined', Icon: LineOutlined },
  { label: 'LinkOutlined', Icon: LinkOutlined },
  { label: 'LinkedinFilled', Icon: LinkedinFilled },
  { label: 'LinkedinOutlined', Icon: LinkedinOutlined },
  { label: 'Loading3QuartersOutlined', Icon: Loading3QuartersOutlined },
  { label: 'LoadingOutlined', Icon: LoadingOutlined },
  { label: 'LockFilled', Icon: LockFilled },
  { label: 'LockOutlined', Icon: LockOutlined },
  { label: 'LockTwoTone', Icon: LockTwoTone },
  { label: 'LoginOutlined', Icon: LoginOutlined },
  { label: 'LogoutOutlined', Icon: LogoutOutlined },
  { label: 'MacCommandFilled', Icon: MacCommandFilled },
  { label: 'MacCommandOutlined', Icon: MacCommandOutlined },
  { label: 'MailFilled', Icon: MailFilled },
  { label: 'MailOutlined', Icon: MailOutlined },
  { label: 'MailTwoTone', Icon: MailTwoTone },
  { label: 'ManOutlined', Icon: ManOutlined },
  { label: 'MedicineBoxFilled', Icon: MedicineBoxFilled },
  { label: 'MedicineBoxOutlined', Icon: MedicineBoxOutlined },
  { label: 'MedicineBoxTwoTone', Icon: MedicineBoxTwoTone },
  { label: 'MediumCircleFilled', Icon: MediumCircleFilled },
  { label: 'MediumOutlined', Icon: MediumOutlined },
  { label: 'MediumSquareFilled', Icon: MediumSquareFilled },
  { label: 'MediumWorkmarkOutlined', Icon: MediumWorkmarkOutlined },
  { label: 'MehFilled', Icon: MehFilled },
  { label: 'MehOutlined', Icon: MehOutlined },
  { label: 'MehTwoTone', Icon: MehTwoTone },
  { label: 'MenuFoldOutlined', Icon: MenuFoldOutlined },
  { label: 'MenuOutlined', Icon: MenuOutlined },
  { label: 'MenuUnfoldOutlined', Icon: MenuUnfoldOutlined },
  { label: 'MergeCellsOutlined', Icon: MergeCellsOutlined },
  { label: 'MessageFilled', Icon: MessageFilled },
  { label: 'MessageOutlined', Icon: MessageOutlined },
  { label: 'MessageTwoTone', Icon: MessageTwoTone },
  { label: 'MinusCircleFilled', Icon: MinusCircleFilled },
  { label: 'MinusCircleOutlined', Icon: MinusCircleOutlined },
  { label: 'MinusCircleTwoTone', Icon: MinusCircleTwoTone },
  { label: 'MinusOutlined', Icon: MinusOutlined },
  { label: 'MinusSquareFilled', Icon: MinusSquareFilled },
  { label: 'MinusSquareOutlined', Icon: MinusSquareOutlined },
  { label: 'MinusSquareTwoTone', Icon: MinusSquareTwoTone },
  { label: 'MobileFilled', Icon: MobileFilled },
  { label: 'MobileOutlined', Icon: MobileOutlined },
  { label: 'MobileTwoTone', Icon: MobileTwoTone },
  { label: 'MoneyCollectFilled', Icon: MoneyCollectFilled },
  { label: 'MoneyCollectOutlined', Icon: MoneyCollectOutlined },
  { label: 'MoneyCollectTwoTone', Icon: MoneyCollectTwoTone },
  { label: 'MonitorOutlined', Icon: MonitorOutlined },
  { label: 'MoreOutlined', Icon: MoreOutlined },
  { label: 'NodeCollapseOutlined', Icon: NodeCollapseOutlined },
  { label: 'NodeExpandOutlined', Icon: NodeExpandOutlined },
  { label: 'NodeIndexOutlined', Icon: NodeIndexOutlined },
  { label: 'NotificationFilled', Icon: NotificationFilled },
  { label: 'NotificationOutlined', Icon: NotificationOutlined },
  { label: 'NotificationTwoTone', Icon: NotificationTwoTone },
  { label: 'NumberOutlined', Icon: NumberOutlined },
  { label: 'OneToOneOutlined', Icon: OneToOneOutlined },
  { label: 'OrderedListOutlined', Icon: OrderedListOutlined },
  { label: 'PaperClipOutlined', Icon: PaperClipOutlined },
  { label: 'PartitionOutlined', Icon: PartitionOutlined },
  { label: 'PauseCircleFilled', Icon: PauseCircleFilled },
  { label: 'PauseCircleOutlined', Icon: PauseCircleOutlined },
  { label: 'PauseCircleTwoTone', Icon: PauseCircleTwoTone },
  { label: 'PauseOutlined', Icon: PauseOutlined },
  { label: 'PayCircleFilled', Icon: PayCircleFilled },
  { label: 'PayCircleOutlined', Icon: PayCircleOutlined },
  { label: 'PercentageOutlined', Icon: PercentageOutlined },
  { label: 'PhoneFilled', Icon: PhoneFilled },
  { label: 'PhoneOutlined', Icon: PhoneOutlined },
  { label: 'PhoneTwoTone', Icon: PhoneTwoTone },
  { label: 'PicCenterOutlined', Icon: PicCenterOutlined },
  { label: 'PicLeftOutlined', Icon: PicLeftOutlined },
  { label: 'PicRightOutlined', Icon: PicRightOutlined },
  { label: 'PictureFilled', Icon: PictureFilled },
  { label: 'PictureOutlined', Icon: PictureOutlined },
  { label: 'PictureTwoTone', Icon: PictureTwoTone },
  { label: 'PieChartFilled', Icon: PieChartFilled },
  { label: 'PieChartOutlined', Icon: PieChartOutlined },
  { label: 'PieChartTwoTone', Icon: PieChartTwoTone },
  { label: 'PlayCircleFilled', Icon: PlayCircleFilled },
  { label: 'PlayCircleOutlined', Icon: PlayCircleOutlined },
  { label: 'PlayCircleTwoTone', Icon: PlayCircleTwoTone },
  { label: 'PlaySquareFilled', Icon: PlaySquareFilled },
  { label: 'PlaySquareOutlined', Icon: PlaySquareOutlined },
  { label: 'PlaySquareTwoTone', Icon: PlaySquareTwoTone },
  { label: 'PlusCircleFilled', Icon: PlusCircleFilled },
  { label: 'PlusCircleOutlined', Icon: PlusCircleOutlined },
  { label: 'PlusCircleTwoTone', Icon: PlusCircleTwoTone },
  { label: 'PlusOutlined', Icon: PlusOutlined },
  { label: 'PlusSquareFilled', Icon: PlusSquareFilled },
  { label: 'PlusSquareOutlined', Icon: PlusSquareOutlined },
  { label: 'PlusSquareTwoTone', Icon: PlusSquareTwoTone },
  { label: 'PoundCircleFilled', Icon: PoundCircleFilled },
  { label: 'PoundCircleOutlined', Icon: PoundCircleOutlined },
  { label: 'PoundCircleTwoTone', Icon: PoundCircleTwoTone },
  { label: 'PoundOutlined', Icon: PoundOutlined },
  { label: 'PoweroffOutlined', Icon: PoweroffOutlined },
  { label: 'PrinterFilled', Icon: PrinterFilled },
  { label: 'PrinterOutlined', Icon: PrinterOutlined },
  { label: 'PrinterTwoTone', Icon: PrinterTwoTone },
  { label: 'ProfileFilled', Icon: ProfileFilled },
  { label: 'ProfileOutlined', Icon: ProfileOutlined },
  { label: 'ProfileTwoTone', Icon: ProfileTwoTone },
  { label: 'ProjectFilled', Icon: ProjectFilled },
  { label: 'ProjectOutlined', Icon: ProjectOutlined },
  { label: 'ProjectTwoTone', Icon: ProjectTwoTone },
  { label: 'PropertySafetyFilled', Icon: PropertySafetyFilled },
  { label: 'PropertySafetyOutlined', Icon: PropertySafetyOutlined },
  { label: 'PropertySafetyTwoTone', Icon: PropertySafetyTwoTone },
  { label: 'PullRequestOutlined', Icon: PullRequestOutlined },
  { label: 'PushpinFilled', Icon: PushpinFilled },
  { label: 'PushpinOutlined', Icon: PushpinOutlined },
  { label: 'PushpinTwoTone', Icon: PushpinTwoTone },
  { label: 'QqCircleFilled', Icon: QqCircleFilled },
  { label: 'QqOutlined', Icon: QqOutlined },
  { label: 'QqSquareFilled', Icon: QqSquareFilled },
  { label: 'QrcodeOutlined', Icon: QrcodeOutlined },
  { label: 'QuestionCircleFilled', Icon: QuestionCircleFilled },
  { label: 'QuestionCircleOutlined', Icon: QuestionCircleOutlined },
  { label: 'QuestionCircleTwoTone', Icon: QuestionCircleTwoTone },
  { label: 'QuestionOutlined', Icon: QuestionOutlined },
  { label: 'RadarChartOutlined', Icon: RadarChartOutlined },
  { label: 'RadiusBottomleftOutlined', Icon: RadiusBottomleftOutlined },
  { label: 'RadiusBottomrightOutlined', Icon: RadiusBottomrightOutlined },
  { label: 'RadiusSettingOutlined', Icon: RadiusSettingOutlined },
  { label: 'RadiusUpleftOutlined', Icon: RadiusUpleftOutlined },
  { label: 'RadiusUprightOutlined', Icon: RadiusUprightOutlined },
  { label: 'ReadFilled', Icon: ReadFilled },
  { label: 'ReadOutlined', Icon: ReadOutlined },
  { label: 'ReconciliationFilled', Icon: ReconciliationFilled },
  { label: 'ReconciliationOutlined', Icon: ReconciliationOutlined },
  { label: 'ReconciliationTwoTone', Icon: ReconciliationTwoTone },
  { label: 'RedEnvelopeFilled', Icon: RedEnvelopeFilled },
  { label: 'RedEnvelopeOutlined', Icon: RedEnvelopeOutlined },
  { label: 'RedEnvelopeTwoTone', Icon: RedEnvelopeTwoTone },
  { label: 'RedditCircleFilled', Icon: RedditCircleFilled },
  { label: 'RedditOutlined', Icon: RedditOutlined },
  { label: 'RedditSquareFilled', Icon: RedditSquareFilled },
  { label: 'RedoOutlined', Icon: RedoOutlined },
  { label: 'ReloadOutlined', Icon: ReloadOutlined },
  { label: 'RestFilled', Icon: RestFilled },
  { label: 'RestOutlined', Icon: RestOutlined },
  { label: 'RestTwoTone', Icon: RestTwoTone },
  { label: 'RetweetOutlined', Icon: RetweetOutlined },
  { label: 'RightCircleFilled', Icon: RightCircleFilled },
  { label: 'RightCircleOutlined', Icon: RightCircleOutlined },
  { label: 'RightCircleTwoTone', Icon: RightCircleTwoTone },
  { label: 'RightOutlined', Icon: RightOutlined },
  { label: 'RightSquareFilled', Icon: RightSquareFilled },
  { label: 'RightSquareOutlined', Icon: RightSquareOutlined },
  { label: 'RightSquareTwoTone', Icon: RightSquareTwoTone },
  { label: 'RiseOutlined', Icon: RiseOutlined },
  { label: 'RobotFilled', Icon: RobotFilled },
  { label: 'RobotOutlined', Icon: RobotOutlined },
  { label: 'RocketFilled', Icon: RocketFilled },
  { label: 'RocketOutlined', Icon: RocketOutlined },
  { label: 'RocketTwoTone', Icon: RocketTwoTone },
  { label: 'RollbackOutlined', Icon: RollbackOutlined },
  { label: 'RotateLeftOutlined', Icon: RotateLeftOutlined },
  { label: 'RotateRightOutlined', Icon: RotateRightOutlined },
  { label: 'SafetyCertificateFilled', Icon: SafetyCertificateFilled },
  { label: 'SafetyCertificateOutlined', Icon: SafetyCertificateOutlined },
  { label: 'SafetyCertificateTwoTone', Icon: SafetyCertificateTwoTone },
  { label: 'SafetyOutlined', Icon: SafetyOutlined },
  { label: 'SaveFilled', Icon: SaveFilled },
  { label: 'SaveOutlined', Icon: SaveOutlined },
  { label: 'SaveTwoTone', Icon: SaveTwoTone },
  { label: 'ScanOutlined', Icon: ScanOutlined },
  { label: 'ScheduleFilled', Icon: ScheduleFilled },
  { label: 'ScheduleOutlined', Icon: ScheduleOutlined },
  { label: 'ScheduleTwoTone', Icon: ScheduleTwoTone },
  { label: 'ScissorOutlined', Icon: ScissorOutlined },
  { label: 'SearchOutlined', Icon: SearchOutlined },
  { label: 'SecurityScanFilled', Icon: SecurityScanFilled },
  { label: 'SecurityScanOutlined', Icon: SecurityScanOutlined },
  { label: 'SecurityScanTwoTone', Icon: SecurityScanTwoTone },
  { label: 'SelectOutlined', Icon: SelectOutlined },
  { label: 'SendOutlined', Icon: SendOutlined },
  { label: 'SettingFilled', Icon: SettingFilled },
  { label: 'SettingOutlined', Icon: SettingOutlined },
  { label: 'SettingTwoTone', Icon: SettingTwoTone },
  { label: 'ShakeOutlined', Icon: ShakeOutlined },
  { label: 'ShareAltOutlined', Icon: ShareAltOutlined },
  { label: 'ShopFilled', Icon: ShopFilled },
  { label: 'ShopOutlined', Icon: ShopOutlined },
  { label: 'ShopTwoTone', Icon: ShopTwoTone },
  { label: 'ShoppingCartOutlined', Icon: ShoppingCartOutlined },
  { label: 'ShoppingFilled', Icon: ShoppingFilled },
  { label: 'ShoppingOutlined', Icon: ShoppingOutlined },
  { label: 'ShoppingTwoTone', Icon: ShoppingTwoTone },
  { label: 'ShrinkOutlined', Icon: ShrinkOutlined },
  { label: 'SignalFilled', Icon: SignalFilled },
  { label: 'SisternodeOutlined', Icon: SisternodeOutlined },
  { label: 'SketchCircleFilled', Icon: SketchCircleFilled },
  { label: 'SketchOutlined', Icon: SketchOutlined },
  { label: 'SketchSquareFilled', Icon: SketchSquareFilled },
  { label: 'SkinFilled', Icon: SkinFilled },
  { label: 'SkinOutlined', Icon: SkinOutlined },
  { label: 'SkinTwoTone', Icon: SkinTwoTone },
  { label: 'SkypeFilled', Icon: SkypeFilled },
  { label: 'SkypeOutlined', Icon: SkypeOutlined },
  { label: 'SlackCircleFilled', Icon: SlackCircleFilled },
  { label: 'SlackOutlined', Icon: SlackOutlined },
  { label: 'SlackSquareFilled', Icon: SlackSquareFilled },
  { label: 'SlackSquareOutlined', Icon: SlackSquareOutlined },
  { label: 'SlidersFilled', Icon: SlidersFilled },
  { label: 'SlidersOutlined', Icon: SlidersOutlined },
  { label: 'SlidersTwoTone', Icon: SlidersTwoTone },
  { label: 'SmallDashOutlined', Icon: SmallDashOutlined },
  { label: 'SmileFilled', Icon: SmileFilled },
  { label: 'SmileOutlined', Icon: SmileOutlined },
  { label: 'SmileTwoTone', Icon: SmileTwoTone },
  { label: 'SnippetsFilled', Icon: SnippetsFilled },
  { label: 'SnippetsOutlined', Icon: SnippetsOutlined },
  { label: 'SnippetsTwoTone', Icon: SnippetsTwoTone },
  { label: 'SolutionOutlined', Icon: SolutionOutlined },
  { label: 'SortAscendingOutlined', Icon: SortAscendingOutlined },
  { label: 'SortDescendingOutlined', Icon: SortDescendingOutlined },
  { label: 'SoundFilled', Icon: SoundFilled },
  { label: 'SoundOutlined', Icon: SoundOutlined },
  { label: 'SoundTwoTone', Icon: SoundTwoTone },
  { label: 'SplitCellsOutlined', Icon: SplitCellsOutlined },
  { label: 'StarFilled', Icon: StarFilled },
  { label: 'StarOutlined', Icon: StarOutlined },
  { label: 'StarTwoTone', Icon: StarTwoTone },
  { label: 'StepBackwardFilled', Icon: StepBackwardFilled },
  { label: 'StepBackwardOutlined', Icon: StepBackwardOutlined },
  { label: 'StepForwardFilled', Icon: StepForwardFilled },
  { label: 'StepForwardOutlined', Icon: StepForwardOutlined },
  { label: 'StockOutlined', Icon: StockOutlined },
  { label: 'StopFilled', Icon: StopFilled },
  { label: 'StopOutlined', Icon: StopOutlined },
  { label: 'StopTwoTone', Icon: StopTwoTone },
  { label: 'StrikethroughOutlined', Icon: StrikethroughOutlined },
  { label: 'SubnodeOutlined', Icon: SubnodeOutlined },
  { label: 'SwapLeftOutlined', Icon: SwapLeftOutlined },
  { label: 'SwapOutlined', Icon: SwapOutlined },
  { label: 'SwapRightOutlined', Icon: SwapRightOutlined },
  { label: 'SwitcherFilled', Icon: SwitcherFilled },
  { label: 'SwitcherOutlined', Icon: SwitcherOutlined },
  { label: 'SwitcherTwoTone', Icon: SwitcherTwoTone },
  { label: 'SyncOutlined', Icon: SyncOutlined },
  { label: 'TableOutlined', Icon: TableOutlined },
  { label: 'TabletFilled', Icon: TabletFilled },
  { label: 'TabletOutlined', Icon: TabletOutlined },
  { label: 'TabletTwoTone', Icon: TabletTwoTone },
  { label: 'TagFilled', Icon: TagFilled },
  { label: 'TagOutlined', Icon: TagOutlined },
  { label: 'TagTwoTone', Icon: TagTwoTone },
  { label: 'TagsFilled', Icon: TagsFilled },
  { label: 'TagsOutlined', Icon: TagsOutlined },
  { label: 'TagsTwoTone', Icon: TagsTwoTone },
  { label: 'TaobaoCircleFilled', Icon: TaobaoCircleFilled },
  { label: 'TaobaoCircleOutlined', Icon: TaobaoCircleOutlined },
  { label: 'TaobaoOutlined', Icon: TaobaoOutlined },
  { label: 'TaobaoSquareFilled', Icon: TaobaoSquareFilled },
  { label: 'TeamOutlined', Icon: TeamOutlined },
  { label: 'ThunderboltFilled', Icon: ThunderboltFilled },
  { label: 'ThunderboltOutlined', Icon: ThunderboltOutlined },
  { label: 'ThunderboltTwoTone', Icon: ThunderboltTwoTone },
  { label: 'ToTopOutlined', Icon: ToTopOutlined },
  { label: 'ToolFilled', Icon: ToolFilled },
  { label: 'ToolOutlined', Icon: ToolOutlined },
  { label: 'ToolTwoTone', Icon: ToolTwoTone },
  { label: 'TrademarkCircleFilled', Icon: TrademarkCircleFilled },
  { label: 'TrademarkCircleOutlined', Icon: TrademarkCircleOutlined },
  { label: 'TrademarkCircleTwoTone', Icon: TrademarkCircleTwoTone },
  { label: 'TrademarkOutlined', Icon: TrademarkOutlined },
  { label: 'TransactionOutlined', Icon: TransactionOutlined },
  { label: 'TranslationOutlined', Icon: TranslationOutlined },
  { label: 'TrophyFilled', Icon: TrophyFilled },
  { label: 'TrophyOutlined', Icon: TrophyOutlined },
  { label: 'TrophyTwoTone', Icon: TrophyTwoTone },
  { label: 'TwitterCircleFilled', Icon: TwitterCircleFilled },
  { label: 'TwitterOutlined', Icon: TwitterOutlined },
  { label: 'TwitterSquareFilled', Icon: TwitterSquareFilled },
  { label: 'UnderlineOutlined', Icon: UnderlineOutlined },
  { label: 'UndoOutlined', Icon: UndoOutlined },
  { label: 'UngroupOutlined', Icon: UngroupOutlined },
  { label: 'UnlockFilled', Icon: UnlockFilled },
  { label: 'UnlockOutlined', Icon: UnlockOutlined },
  { label: 'UnlockTwoTone', Icon: UnlockTwoTone },
  { label: 'UnorderedListOutlined', Icon: UnorderedListOutlined },
  { label: 'UpCircleFilled', Icon: UpCircleFilled },
  { label: 'UpCircleOutlined', Icon: UpCircleOutlined },
  { label: 'UpCircleTwoTone', Icon: UpCircleTwoTone },
  { label: 'UpOutlined', Icon: UpOutlined },
  { label: 'UpSquareFilled', Icon: UpSquareFilled },
  { label: 'UpSquareOutlined', Icon: UpSquareOutlined },
  { label: 'UpSquareTwoTone', Icon: UpSquareTwoTone },
  { label: 'UploadOutlined', Icon: UploadOutlined },
  { label: 'UsbFilled', Icon: UsbFilled },
  { label: 'UsbOutlined', Icon: UsbOutlined },
  { label: 'UsbTwoTone', Icon: UsbTwoTone },
  { label: 'UserAddOutlined', Icon: UserAddOutlined },
  { label: 'UserDeleteOutlined', Icon: UserDeleteOutlined },
  { label: 'UserOutlined', Icon: UserOutlined },
  { label: 'UserSwitchOutlined', Icon: UserSwitchOutlined },
  { label: 'UsergroupAddOutlined', Icon: UsergroupAddOutlined },
  { label: 'UsergroupDeleteOutlined', Icon: UsergroupDeleteOutlined },
  { label: 'VerifiedOutlined', Icon: VerifiedOutlined },
  { label: 'VerticalAlignBottomOutlined', Icon: VerticalAlignBottomOutlined },
  { label: 'VerticalAlignMiddleOutlined', Icon: VerticalAlignMiddleOutlined },
  { label: 'VerticalAlignTopOutlined', Icon: VerticalAlignTopOutlined },
  { label: 'VerticalLeftOutlined', Icon: VerticalLeftOutlined },
  { label: 'VerticalRightOutlined', Icon: VerticalRightOutlined },
  { label: 'VideoCameraAddOutlined', Icon: VideoCameraAddOutlined },
  { label: 'VideoCameraFilled', Icon: VideoCameraFilled },
  { label: 'VideoCameraOutlined', Icon: VideoCameraOutlined },
  { label: 'VideoCameraTwoTone', Icon: VideoCameraTwoTone },
  { label: 'WalletFilled', Icon: WalletFilled },
  { label: 'WalletOutlined', Icon: WalletOutlined },
  { label: 'WalletTwoTone', Icon: WalletTwoTone },
  { label: 'WarningFilled', Icon: WarningFilled },
  { label: 'WarningOutlined', Icon: WarningOutlined },
  { label: 'WarningTwoTone', Icon: WarningTwoTone },
  { label: 'WechatFilled', Icon: WechatFilled },
  { label: 'WechatOutlined', Icon: WechatOutlined },
  { label: 'WeiboCircleFilled', Icon: WeiboCircleFilled },
  { label: 'WeiboCircleOutlined', Icon: WeiboCircleOutlined },
  { label: 'WeiboOutlined', Icon: WeiboOutlined },
  { label: 'WeiboSquareFilled', Icon: WeiboSquareFilled },
  { label: 'WeiboSquareOutlined', Icon: WeiboSquareOutlined },
  { label: 'WhatsAppOutlined', Icon: WhatsAppOutlined },
  { label: 'WifiOutlined', Icon: WifiOutlined },
  { label: 'WindowsFilled', Icon: WindowsFilled },
  { label: 'WindowsOutlined', Icon: WindowsOutlined },
  { label: 'WomanOutlined', Icon: WomanOutlined },
  { label: 'YahooFilled', Icon: YahooFilled },
  { label: 'YahooOutlined', Icon: YahooOutlined },
  { label: 'YoutubeFilled', Icon: YoutubeFilled },
  { label: 'YoutubeOutlined', Icon: YoutubeOutlined },
  { label: 'YuqueFilled', Icon: YuqueFilled },
  { label: 'YuqueOutlined', Icon: YuqueOutlined },
  { label: 'ZhihuCircleFilled', Icon: ZhihuCircleFilled },
  { label: 'ZhihuOutlined', Icon: ZhihuOutlined },
  { label: 'ZhihuSquareFilled', Icon: ZhihuSquareFilled },
  { label: 'ZoomInOutlined', Icon: ZoomInOutlined },
  { label: 'ZoomOutOutlined', Icon: ZoomOutOutlined }
]
